version: "3.8"

services:
  nuxt-app:
    # image: ttt-ui:latest-production
    container_name: ttt-ui-container
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        IMAGE_NAME: ttt-ui-image
    restart: always
    ports:
      - 80:80
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge
