version: "3.8"

services:
  nuxt-app:
    # image: ttt-ui:latest-production
    container_name: ttt-ui-container
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - 3050:3000
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge
